### ISSUE TITLE
Reloading of all cuboid region files after adding a new one

### ISSUE THREAD

**Issue by Sammi4** [damagefilter/Cuboids#14]
Command: “/cmod add [Area]”
After adding of new region, other regions seem to get unloaded
(It can now be accomplished by restarting the server, IDN if “/reload” would do it)
Sammi4

**Comment by damagefilter** [comment]
Heard that from another place too.
Funny thing. Didn't get that problem so far. Will still have a look around that code.

**Comment by damagefilter** [comment]
Oh, right. That would be fixed. It's also backported to 1.7
